name: Build and Release

on:
  workflow_dispatch:

jobs:
  get-data:
    name: Read Cargo TOML
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Read Cargo TOML
        uses: SebRollen/toml-action@v1.0.2
        id: read_toml
        with:
          file: './web-server/Cargo.toml'
          field: 'package.version'

    outputs:
      version: ${{ steps.read_toml.outputs.value }}
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: get-data
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
    steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Compile Rust
          id: compile
          uses: rust-build/rust-build.action@v1.4.3
          with:
            RUSTTARGET: ${{ matrix.target }}
            ARCHIVE_TYPES: ${{ matrix.archive }}
            TOOLCHAIN_VERSION: nightly
            UPLOAD_MODE: none
            SRC_DIR: ./web-server

        - name: Push Tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            custom_tag: ${{ needs.get-data.outputs.version }}

        - name: Create Release
          uses: ncipollo/release-action@v1
          with:
            tag: ${{ steps.tag_version.outputs.new_tag }}
            name: Release ${{ steps.tag_version.outputs.new_tag }}
            artifacts: ${{ steps.compile.outputs.BUILT_ARCHIVE }}